/* Procedural outdoor flume renderer. Materials, ripples and vegetation are visual;
   all depth/velocity values still come from hydraulics.js. No external assets. */
function createHumpFlume(canvas){
 const gl=canvas.getContext('webgl',{antialias:true,preserveDrawingBuffer:true});if(!gl)throw Error('WebGL is unavailable');
 let yaw=-.62,elev=.67,zoom=1,drag=null,time=0,lastKey='',count=0,bank=2,trees=[];
 const vs=`attribute vec3 p,n,c;attribute float material;uniform float yaw,el,scale,aspect,time,velocity,centerY;varying vec3 pos,normal,color;varying float mat;
 void main(){vec3 q=p;mat=material;normal=n;if(material>2.5&&material<3.5&&n.y>.5){q.y+=.007*sin(q.x*3.8-time*velocity*3.8+sin(q.z*4.))*sin(q.z*6.);}pos=q;color=c;float x=cos(yaw)*q.x-sin(yaw)*q.z;float z=sin(yaw)*q.x+cos(yaw)*q.z;float yy=q.y-centerY;gl_Position=vec4(x*scale/aspect,(z*sin(el)+yy*cos(el))*scale,(z*cos(el)-yy*sin(el))/80.,1.);}`;
 const fs=`precision highp float;varying vec3 pos,normal,color;varying float mat;uniform float time,velocity,width,depth,slope,yaw,el;uniform vec3 treeShadow[12];
 float hash(vec3 p){p=fract(p*.3183099+vec3(.17,.37,.53));p*=17.;return fract(p.x*p.y*p.z*(p.x+p.y+p.z));}
 float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
 void main(){if(mat>8.5){gl_FragColor=vec4(.12,.48,.57,.45);return;}if(mat>7.5){gl_FragColor=vec4(.48,.72,.76,.14);return;}vec3 N=normalize(normal),base=color;float grain=noise(pos*25.),broad=noise(pos*2.3);vec3 light=normalize(vec3(-.45,1.,.5));float diffuse=max(0.,dot(N,light));float shade=.54+.46*diffuse;
 if(mat<.5){base*=.78+.25*noise(pos*7.)+.10*grain;float strata=sin(pos.y*32.+noise(pos*3.)*3.);base*=.94+.06*strata;}
 else if(mat<1.5){base=mix(vec3(.26,.32,.16),vec3(.46,.48,.27),broad)*(.82+.27*grain);base+=vec3(.025,.013,0.)*noise(pos*64.);}
 else if(mat<2.5){base*=.87+.16*grain+.05*broad;float seam=1.-smoothstep(.012,.027,abs(fract((pos.x+12.)/3.)-.5));base*=1.-.24*seam;float level=.3+(12.-pos.x)*slope+depth;float stain=(1.-smoothstep(.05,.55,abs(pos.y-level)))*(1.-abs(N.y));base=mix(base,base*vec3(.69,.76,.63),stain*.4);}
 else if(mat<3.5){vec3 view=normalize(vec3(-sin(yaw)*cos(el),sin(el),-cos(yaw)*cos(el)));float moving=pos.x-time*velocity;float wave1=sin(moving*5.+sin(pos.z*3.4)*1.3),wave2=sin(moving*11.3+pos.z*15.+time*.5);vec3 wn=normalize(vec3(.045*cos(moving*5.+sin(pos.z*3.4)),1.,.035*cos(moving*11.3+pos.z*15.)));float fres=pow(1.-max(0.,dot(wn,view)),4.);float spec=pow(max(0.,dot(reflect(-light,wn),view)),100.);float side=abs(pos.z)/(width*.5);base=mix(vec3(.065,.30,.39),vec3(.12,.40,.49),.5+.14*wave1*wave2+.18*(noise(vec3(moving*.8,0.,pos.z*3.))-.5));base=mix(base,vec3(.52,.68,.71),fres*.65);base+=spec*.6;float edge=smoothstep(.83,1.,side);base*=1.-.33*edge;base+=vec3(.1,.15,.13)*pow(max(0.,wave1*wave2),15.)*.12;if(N.y<.5)base*=.6;gl_FragColor=vec4(base,1.);return;}
 else if(mat<4.5){base*=.72+.3*noise(vec3(pos.x*28.,pos.y*2.,pos.z*28.));}
 else if(mat<5.5){base*=.78+.23*grain+.12*broad;shade=.42+.55*diffuse+.09*max(0.,dot(-N,light));}
 else if(mat<6.5){shade=.6+.4*diffuse;}
 if(mat<2.5){float shadow=0.;for(int i=0;i<12;i++){vec2 d=(pos.xz-treeShadow[i].xz-vec2(.38,-.46))/vec2(.9,.65);shadow=max(shadow,exp(-dot(d,d)*1.5)*.26);}shade*=1.-shadow;float ao=exp(-abs(abs(pos.z)-width*.5)*3.);shade*=1.-ao*.13;}
 gl_FragColor=vec4(base*shade,1.);}`;
 function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s}
 const prog=gl.createProgram();gl.attachShader(prog,shader(gl.VERTEX_SHADER,vs));gl.attachShader(prog,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(prog);if(!gl.getProgramParameter(prog,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(prog));gl.useProgram(prog);const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);for(let [name,size,offset]of [['p',3,0],['n',3,12],['c',3,24],['material',1,36]]){let a=gl.getAttribLocation(prog,name);gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,size,gl.FLOAT,false,40,offset)}const uniforms={};for(let name of ['yaw','el','scale','aspect','time','velocity','centerY','width','depth','slope','treeShadow[0]'])uniforms[name]=gl.getUniformLocation(prog,name);
 let data=[],seed=981;const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296),sub=(a,b)=>a.map((v,i)=>v-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{let d=Math.hypot(...a)||1;return a.map(v=>v/d)};
 function tri(a,b,c,col,mat,ns){let n=norm(cross(sub(b,a),sub(c,a)));for(let [i,p]of [a,b,c].entries())data.push(...p,...(ns?ns[i]:n),...col,mat)}
 function quad(a,b,c,d,col,mat){tri(a,b,c,col,mat);tri(a,c,d,col,mat)}
 function box(x,y,z,w,h,d,col,mat=2){let p=[[x-w/2,y,z-d/2],[x+w/2,y,z-d/2],[x+w/2,y,z+d/2],[x-w/2,y,z+d/2],[x-w/2,y+h,z-d/2],[x+w/2,y+h,z-d/2],[x+w/2,y+h,z+d/2],[x-w/2,y+h,z+d/2]];for(let f of [[4,7,6,5],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]])quad(...f.map(i=>p[i]),col,mat)}
 function cylinder(a,b,r1,r2,col,mat=4){let axis=norm(sub(b,a)),u=norm(cross(axis,[.13,.07,1])),v=cross(axis,u),N=9;for(let i=0;i<N;i++){let pt=(p,r,t)=>p.map((x,j)=>x+r*(u[j]*Math.cos(t)+v[j]*Math.sin(t))),t=i/N*6.283,t2=(i+1)/N*6.283;quad(pt(a,r1,t),pt(a,r1,t2),pt(b,r2,t2),pt(b,r2,t),col,mat)}}
 function ellipsoid(x,y,z,rx,ry,rz,col,mat=5){let N=9,M=6;const point=(i,j)=>{let a=i/N*Math.PI*2,t=j/M*Math.PI,nn=[Math.cos(a)*Math.sin(t),Math.cos(t),Math.sin(a)*Math.sin(t)];return {p:[x+rx*nn[0],y+ry*nn[1],z+rz*nn[2]],n:norm([nn[0]/rx,nn[1]/ry,nn[2]/rz])}};for(let j=0;j<M;j++)for(let i=0;i<N;i++){let a=point(i,j),b=point(i+1,j),c=point(i+1,j+1),d=point(i,j+1);tri(a.p,b.p,c.p,col,mat,[a.n,b.n,c.n]);tri(a.p,c.p,d.p,col,mat,[a.n,c.n,d.n])}}
 let opaqueCount=0;
 function build(r){data=[];seed=981;trees=Array(36).fill(1000);let width=r.b;bank=.3+(.45*24/4.3)+24*r.s;const bed=x=>.3+(12-x)*r.s,point=x=>{let px=(x+12)/24*4.3,a=r.profile;let low=0,high=a.length-1;while(high-low>1){let m=(low+high)>>1;if(a[m].x<px)low=m;else high=m}let t=Math.max(0,Math.min(1,(px-a[low].x)/(a[high].x-a[low].x)));return {water:.3+(a[low].water*(1-t)+a[high].water*t)*24/4.3,hump:(a[low].hump*(1-t)+a[high].hump*t)*24/4.3}},water=x=>point(x).water,orange=[.78,.34,.10],steel=[.36,.43,.43];
 // Elevated glass-sided tilting bench, frame, collection tank and recirculation pump.
 box(0,-1.5,0,28,.18,7,[.53,.55,.53],2);
 for(let x of [-9,-3,3,9]){box(x,-1.32,0,.26,1.5,2.3,steel,6);box(x,-1.32,0,1,.12,3.2,steel,6)}
 for(let side of [-1,1])box(0,-.10,side*(width/2+.22),24.5,.27,.25,steel,6);
 box(-12.9,.3,-.02,1.7,bank-.15,width+.5,orange,6);box(12.7,-.7,0,1.3,1.5,width+.6,orange,6);
 box(-8,-1.3,2.1,5,.9,1.2,[.4,.46,.46],6);cylinder([-9,-.55,2.2],[-11,-.55,2.2],.28,.28,[.21,.34,.35],6);cylinder([-11,-.55,2.2],[-12.8,bank-.1,0],.1,.1,[.46,.5,.48],6);cylinder([12.6,-.4,0],[11.8,-1,2.1],.11,.11,[.43,.48,.47],6);cylinder([11.8,-1,2.1],[-8,-1,2.1],.11,.11,[.43,.48,.47],6);
 for(let i=0;i<120;i++){let x=-12+i*.2,xx=x+.2;quad([x,bed(x),-width/2],[x,bed(x),width/2],[xx,bed(xx),width/2],[xx,bed(xx),-width/2],[.69,.71,.68],6);for(let side of [-1,1]){box(x+.1,bed(x+.1)-.13,side*(width/2+.09),.202,.16,.18,orange,6);box(x+.1,bed(x+.1)+.45*24/4.3,side*(width/2+.09),.202,.12,.18,orange,6)}if(r.y>0)for(let j=0;j<12;j++){let z=-width/2+j*width/12,zz=z+width/12;quad([x,water(x),z],[x,water(x),zz],[xx,water(xx),zz],[xx,water(xx),z],[.1,.4,.5],3)}}
 for(let x of [-9,-3,3,9])for(let side of [-1,1])box(x,bed(x),side*(width/2+.09),.13,.45*24/4.3,.18,orange,6);
 for(let x of [-8,0,8]){let top=bed(x)+.45*24/4.3+.18;box(x,top,0,.4,.10,width+.6,steel,6);cylinder([x,water(x),0],[x,top+.7,0],.023,.023,[.8,.81,.77],6);box(x,top+.35,.04,.12,.22,.15,[.84,.82,.67],7);for(let j=0;j<10;j++)box(x,top+j*.06,0,.08,.012,.03,[.1,.12,.13],7)}
 for(let i=0;i<240;i++){let x=-12+i*.1,xx=x+.1,h=point(x).hump,hh=point(xx).hump;if(h>0||hh>0){quad([x,bed(x)+h,-width/2],[x,bed(x)+h,width/2],[xx,bed(xx)+hh,width/2],[xx,bed(xx)+hh,-width/2],[.67,.47,.25],2);for(let side of [-1,1])quad([x,bed(x),side*width/2],[xx,bed(xx),side*width/2],[xx,bed(xx)+hh,side*width/2],[x,bed(x)+h,side*width/2],[.66,.45,.23],2)}}
 opaqueCount=data.length/10;
 if(r.y>0)for(let i=0;i<120;i++){let x=-12+i*.2,xx=x+.2;for(let side of [-1,1])quad([x,bed(x),side*width/2],[xx,bed(xx),side*width/2],[xx,water(xx),side*width/2],[x,water(x),side*width/2],[.1,.4,.5],9);}

 for(let side of [-1,1])quad([-12,bed(-12),side*(width/2+.05)],[12,bed(12),side*(width/2+.05)],[12,bed(12)+.45*24/4.3,side*(width/2+.05)],[-12,bed(-12)+.45*24/4.3,side*(width/2+.05)],[.5,.7,.8],8);
 count=data.length/10;gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);gl.uniform3fv(uniforms['treeShadow[0]'],new Float32Array(trees));}
 function draw(dt,r,animate){r={...r,b:r.b*24/4.3,y:r.y*24/4.3,V:r.V*24/4.3};if(animate)time+=dt;let key=[r.b,r.y,r.s,r.height,r.type,r.ponding,r.Q].join('/');if(key!==lastKey){build(r);lastKey=key}let ratio=Math.min(devicePixelRatio||1,2),w=Math.round(canvas.clientWidth*ratio),h=Math.round(canvas.clientHeight*ratio);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}gl.viewport(0,0,w,h);gl.clearColor(.61,.63,.61,1);gl.enable(gl.DEPTH_TEST);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);for(let [k,v]of Object.entries({yaw,el:elev,scale:.086*zoom/Math.max(1,(bank+4)/9),aspect:w/Math.max(1,h),time,velocity:r.V,centerY:bank*.48,width:r.b,depth:r.y,slope:r.s}))gl.uniform1f(uniforms[k],v);gl.disable(gl.BLEND);gl.depthMask(true);gl.drawArrays(gl.TRIANGLES,0,opaqueCount);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(false);gl.drawArrays(gl.TRIANGLES,opaqueCount,count-opaqueCount);gl.depthMask(true);gl.disable(gl.BLEND)}
 canvas.addEventListener('pointerdown',e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.006;elev=Math.max(.2,Math.min(1.3,elev-(e.clientY-drag[1])*.006));drag=[e.clientX,e.clientY]});const stop=()=>drag=null;canvas.addEventListener('pointerup',stop);canvas.addEventListener('pointercancel',stop);canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.55,Math.min(1.8,zoom*Math.exp(-e.deltaY*.001)))},{passive:false});return {draw,reset:()=>{yaw=-.62;elev=.67;zoom=1},error:()=>gl.getError()};
}
