const $=id=>document.getElementById(id),scene=createHumpFlume($('scene')),fmt=(v,d=4)=>Number(v).toFixed(d);
let model,observed=null,rows=[],origin='manual entry',animated=!matchMedia('(prefers-reduced-motion: reduce)').matches,last=0;
const names=['Upstream','Crest','Downstream'];
names.forEach((name,i)=>{let h=document.createElement('h3');h.textContent=name+' local depths (m)';$('gaugeFields').append(h);let g=document.createElement('div');g.className='gauges';for(let j=0;j<3;j++){let l=document.createElement('label');l.textContent='Reading '+(j+1);let n=document.createElement('input');n.id='g'+(i*3+j);n.type='number';n.min='.0001';n.max='.45';n.step='.0001';n.setAttribute('aria-label',name+' reading '+(j+1)+' in metres');n.oninput=()=>{origin='manual entry';observed=null;plot()};l.append(n);g.append(l)}$('gaugeFields').append(g)});
function setup(){model=HumpLab.solve({Q:+$('Q').value/1000,type:$('type').value,height:+$('height').value,ponding:+$('ponding').value});observed=null;for(let i=0;i<9;i++)$('g'+i).value='';$('QOut').textContent=fmt(model.Q*1000,1)+' L/s';$('heightOut').textContent=fmt(model.height,3)+' m';$('pondingOut').textContent=fmt(model.ponding,3)+' m';for(let [id,v] of [['upDepth',model.up.depth],['crestDepth',model.over.depth],['downDepth',model.down.depth],['afflux',model.afflux]])$(id).textContent=fmt(v);$('sceneLabel').textContent=model.controlled?'Critical crest · free downstream flow':'Subcritical flow across the insert';$('control').textContent=model.controlled?'Crest controls the flow: upstream water rises, the crest reaches Fr = 1, and the downstream flow becomes supercritical.':'Available energy exceeds the critical minimum: flow remains subcritical across the hump.';$('critical').textContent=`Critical depth yc = ${fmt(model.yc)} m. Minimum specific energy = ${fmt(model.Emin)} m. Approximate control threshold at this crest position: hump height ${fmt(model.criticalHeight)} m.`;$('sample').disabled=!model.withinFlume;$('message').textContent='Take fresh readings after changing the setup.';plot()}
function calculate(){try{let values=Array.from({length:9},(_,i)=>{if(!$('g'+i).value.trim())throw Error('Enter all nine local depth readings.');return +$('g'+i).value});observed=HumpLab.measurements({Q:model.Q,type:model.type,height:model.height,values});$('message').className='hint';$('message').textContent=observed.sections.map((s,i)=>`${names[i]}: mean ${fmt(s.y)} m, Fr ${fmt(s.Fr,3)} (${Math.abs(s.Fr-1)<.02?'near critical':s.Fr>1?'supercritical':'subcritical'})`).join(' · ')+'. '+origin+'.';plot();return true}catch(e){observed=null;$('message').className='hint error';$('message').textContent=e.message;plot();return false}}
function plot(){if(!model)return;let c=$('humpPlot'),ctx=c.getContext('2d'),max=Math.max(model.totalHead*1.2,.1,...(observed?observed.sections.map((s,i)=>s.y+[model.up,model.over,model.down][i].bed):[]))*1.05,X=x=>75+x/4.3*885,Y=y=>355-y/max*310;ctx.clearRect(0,0,1000,420);ctx.font='16px system-ui';ctx.fillStyle='#adc1c6';for(let i=0;i<=5;i++){let y=max*i/5;ctx.fillText(fmt(y,3),8,Y(y)+5);ctx.strokeStyle='#36515e';ctx.beginPath();ctx.moveTo(75,Y(y));ctx.lineTo(960,Y(y));ctx.stroke();let x=4.3*i/5;ctx.fillText(fmt(x,2),X(x)-16,380)}ctx.fillText('Distance along flume (m)',400,410);ctx.fillText('Elevation / head (m)',75,25);ctx.beginPath();ctx.moveTo(X(0),Y(0));model.profile.forEach(p=>ctx.lineTo(X(p.x),Y(p.bed)));ctx.lineTo(X(4.3),Y(0));ctx.closePath();ctx.fillStyle='#97764e';ctx.fill();ctx.beginPath();model.profile.forEach((p,i)=>i?ctx.lineTo(X(p.x),Y(p.water)):ctx.moveTo(X(p.x),Y(p.water)));ctx.strokeStyle='#78cfff';ctx.lineWidth=3;ctx.stroke();ctx.strokeStyle='#edc485';ctx.setLineDash([7,7]);ctx.beginPath();ctx.moveTo(X(0),Y(model.totalHead));ctx.lineTo(X(4.3),Y(model.totalHead));ctx.stroke();ctx.setLineDash([]);if(observed)observed.sections.forEach((s,i)=>{let p=[model.up,model.over,model.down][i];ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(X(p.x),Y(p.bed+s.y),6,0,Math.PI*2);ctx.fill()})}
function render(){let body=$('trials');body.replaceChildren();rows.forEach(r=>{let tr=document.createElement('tr');for(let v of [r.type,fmt(r.Q,5),fmt(r.height),fmt(r.yc),...r.sections.map(s=>fmt(s.y)),...r.sections.map(s=>fmt(s.Fr,3))]){let td=document.createElement('td');td.textContent=v;tr.append(td)}body.append(tr)});$('progress').textContent=`${rows.filter(r=>r.type==='round').length} rounded and ${rows.filter(r=>r.type==='sharp').length} sharp-insert trials recorded. Compare several discharges for each insert.`}
for(let id of ['Q','height','ponding'])$(id).oninput=setup;
$('type').onchange=()=>{$('height').value=$('type').value==='round'?.12:.06;setup()};$('resetInsert').onclick=()=>{$('height').value=$('type').value==='round'?.12:.06;setup()};$('sample').onclick=()=>{[model.up,model.over,model.down].forEach((s,i)=>{for(let j=0;j<3;j++)$('g'+(i*3+j)).value=fmt(s.depth)});origin='synthetic lossless-model gauges';calculate()};$('calculate').onclick=calculate;$('record').onclick=()=>{if(calculate()){rows.push({...observed,ponding:model.ponding,origin,predicted:[model.up.depth,model.over.depth,model.down.depth],afflux:model.afflux});render()}};
function csv(){return ['insert,Q_m3_s,height_m,extra_upstream_depth_m,yc_m,up1_m,up2_m,up3_m,crest1_m,crest2_m,crest3_m,down1_m,down2_m,down3_m,up_mean_m,crest_mean_m,down_mean_m,Fr_up,Fr_crest,Fr_down,predicted_up_m,predicted_crest_m,predicted_down_m,predicted_afflux_m,origin',...rows.map(r=>[r.type,r.Q,r.height,r.ponding,r.yc,...r.sections.flatMap(s=>s.readings),...r.sections.map(s=>s.y),...r.sections.map(s=>s.Fr),...r.predicted,r.afflux,r.origin].join(','))].join('\n')}
$('export').onclick=()=>{let u=URL.createObjectURL(new Blob([csv()],{type:'text/csv'})),a=document.createElement('a');a.href=u;a.download='manual-experiment-3.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('pause').textContent=animated?'Pause flow':'Animate flow';$('pause').onclick=()=>{animated=!animated;$('pause').textContent=animated?'Pause flow':'Animate flow'};$('view').onclick=scene.reset;setup();render();function frame(t){scene.draw(Math.min(.1,(t-last)/1000||0),{...model,y:model.up.depth,V:model.up.V,s:model.S},animated);last=t;requestAnimationFrame(frame)}requestAnimationFrame(frame);window.humpLab={getState:()=>({model,observed,rows,webglError:scene.error()}),csv};
