/* Manual Experiment 3, pp.22–33. Ideal short-reach Bernoulli + critical control.
   Hydrostatic sections, alpha=1, no local losses or tailwater submergence.
   Sharp-edge separation and jet curvature are not resolved. */
(function(root){const E=root.EnergyLab||(typeof require==='function'?require('./energy.js'):null),H=root.Hydraulics||(typeof require==='function'?require('./hydraulics.js'):null),L=4.3;
function humpAt(x,height,type){let start=1.95,end=2.35;if(x<start||x>end)return 0;if(type==='sharp')return height;let edge=.08,t=Math.min((x-start)/edge,(end-x)/edge,1);return height*(.5-.5*Math.cos(Math.PI*t))}
function solve({Q=.009,type='round',height=type==='round'?.12:.06,ponding=0,S=.002}={}){if(!['round','sharp'].includes(type)||![Q,height,ponding,S].every(Number.isFinite)||Q<=0||Q>.03||height<0||height>.2||ponding<0||ponding>.15||S<=0||S>.01)throw Error('Unsupported hump inputs');let b=.3,normal=H.solve({Q,b,n:.01,s:S}),yc=normal.yc,Emin=1.5*yc,initialDepth=Math.max(normal.y,yc*1.001)+ponding,upX=0,initialHead=(L-upX)*S+E.evaluate(Q,b,initialDepth).E;
let coords=Array.from({length:861},(_,i)=>i*L/860);coords.push(1.95,2.03,2.15,2.27,2.35);coords=[...new Set(coords)].sort((a,b)=>a-b);let base=coords.map(x=>({x,hump:humpAt(x,height,type),bed:(L-x)*S+humpAt(x,height,type)})),crest=base.reduce((a,b)=>b.bed>a.bed?b:a),requiredHead=crest.bed+Emin,totalHead=Math.max(initialHead,requiredHead),controlled=height>0&&initialHead<=requiredHead+1e-10;
function section(p){let available=totalHead-p.bed;if(available<Emin&&available>Emin-1e-10)available=Emin;let roots=E.alternate(Q,b,available).depths;if(!roots.length)throw Error('Energy below critical minimum');let depth=controlled&&p.x>crest.x?roots[0]:roots[roots.length-1];return {...p,...E.evaluate(Q,b,depth),x:p.x,depth,water:p.bed+depth,branch:depth<yc?'supercritical':depth>yc?'subcritical':'critical'}}
let profile=base.map(section),up=section({x:upX,hump:0,bed:(L-upX)*S}),over=section(crest),down=section({x:3.3,hump:0,bed:(L-3.3)*S});return {Q,b,S,type,height,ponding,yc,Emin,initialDepth,totalHead,initialHead,controlled,afflux:Math.max(0,up.depth-initialDepth),criticalHeight:Math.max(0,initialHead-Emin-(crest.bed-crest.hump)),up,over,down,profile,crestX:crest.x,withinFlume:profile.every(p=>p.water-(L-p.x)*S<=.45+1e-9)}}
function measurements({Q,type,height,values}){if(!Array.isArray(values)||values.length!==9||values.some(v=>!Number.isFinite(v)||v<=0||v>.45))throw Error('Enter nine positive local depths, each at most 0.45 m.');let sections=[0,1,2].map(i=>{let a=values.slice(i*3,i*3+3),y=a.reduce((s,v)=>s+v,0)/3;return {...E.evaluate(Q,.3,y),readings:a,spread:Math.max(...a)-Math.min(...a)}});return {Q,type,height,sections,yc:sections[0].yc}}
const api={solve,humpAt,measurements};root.HumpLab=api;if(typeof module!=='undefined')module.exports=api})(typeof window!=='undefined'?window:globalThis);

