const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d');let yaw=-.6,el=.72,zoom=1,time=0,running=!matchMedia('(prefers-reduced-motion: reduce)').matches,drag=null,selected=0;
const sites=[['Overview',0,0,'1:50 physical model','A 1,350 m² laboratory model represented about 3.4 km² of the New Orleans lakefront region.'],['Lake Pontchartrain',0,-5,'Lake wave boundary','The lake supplies the incident wave conditions; this animation is illustrative.'],['Harbor approaches',0,-1,'Harbors and shallow margins','Shallows, harbor walls and the bridge attenuated waves on their way toward the canal.'],['Hammond Highway Bridge',0,1.4,'Bridge crossing','The physical study examined wave transmission and reflection at this crossing.'],['Breach vicinity',1,4.5,'East-bank breach vicinity','The marker locates the general study area. Neither breach geometry nor soil failure is simulated.']];
$('title').textContent='17th Street Canal · lake-to-canal basin';$('subtitle').textContent='A schematic reconstruction of the laboratory setting in Figure 1';$('figure').textContent='Figure 1 · fixed-bed · source model 1:50';$('facts').innerHTML='<span>Coastal</span><span>Fixed bed</span><span>3D basin</span><span>Site-specific source</span>';$('purpose').textContent='The published study found that waves were strongly attenuated before reaching the breach, rather than being a major driver of floodwall failure.';$('detail').textContent='Reported prototype wave heights: 1.8–2.7 m in the open lake, 0.3–0.9 m on the lake side of the bridge, and below 0.3 m on its south side near the breach. These are reported ranges, not outputs from this scene. Source: Seabergh (2010).';
sites.forEach((s,i)=>{let b=document.createElement('button');b.className='item'+(!i?' active':'');b.innerHTML=s[0]+'<small>'+s[3]+'</small>';b.onclick=()=>{selected=i;document.querySelectorAll('.item').forEach((e,j)=>e.classList.toggle('active',i===j));$('figure').textContent=s[0]+' · '+s[4]};$('library').append(b)});
function terrain(x,z){if(z<-.8)return -.35+.10*Math.sin(x*.7)*Math.cos(z);if(z<1){let harbor=(x>-5&&x<-1.5)||(x>1.5&&x<5);return Math.abs(x)<.8||harbor?-.22:.38}if(Math.abs(x)<.62)return -.22;let levee=Math.abs(x)<1.05;return levee?.60:.28+.045*Math.sin(x*1.4)*Math.sin(z*.8)}
function draw(){let dpr=Math.min(devicePixelRatio,1.5),w=canvas.clientWidth,h=canvas.clientHeight;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);let sc=Math.min(w/22,h/19)*zoom,polys=[];
function project(p){let [x,y,z]=p,xx=x*Math.cos(yaw)-z*Math.sin(yaw),zz=x*Math.sin(yaw)+z*Math.cos(yaw);return [w/2+xx*sc,h*.54+(zz*Math.sin(el)-y*Math.cos(el))*sc,zz*Math.cos(el)+y*Math.sin(el)]}
function poly(v,col){let p=v.map(project);polys.push({p,col,depth:p.reduce((s,a)=>s+a[2],0)/p.length})}
function box(x,y,z,b,d,ht,col){let a=[x-b/2,y,z-d/2],c=[x+b/2,y,z+d/2];poly([[a[0],y+ht,a[2]],[c[0],y+ht,a[2]],[c[0],y+ht,c[2]],[a[0],y+ht,c[2]]],col);for(let q of [[[a[0],a[2]],[c[0],a[2]]],[[c[0],a[2]],[c[0],c[2]]],[[c[0],c[2]],[a[0],c[2]]],[[a[0],c[2]],[a[0],a[2]]]])poly([[q[0][0],y,q[0][1]],[q[1][0],y,q[1][1]],[q[1][0],y+ht,q[1][1]],[q[0][0],y+ht,q[0][1]]],col)}
box(0,-.8,0,16.6,16.6,.35,'#69746c');polys.forEach(p=>p.depth-=10000);let level=+$('level').value,amp=+$('waves').value;
for(let iz=0;iz<64;iz++)for(let ix=0;ix<64;ix++){let x=-8+ix*.25,z=-8+iz*.25,y=terrain(x+.125,z+.125),wet=y<level,noise=Math.sin(ix*43+iz*27)*3;let col=wet?`rgb(${45+noise},${124+noise},${146+noise})`:`rgb(${194+noise},${173+noise},${92+noise})`;let v=[[x,y,z],[x+.25,y,z],[x+.25,y,z+.25],[x,y,z+.25]];if(wet){let attenuation=z<-.8?1:z<1.4?.35:.10;v=v.map(([a,b,c])=>[a,level+.035*amp*attenuation*Math.sin((c*Math.cos((window.paperVisual?.dir||0)*Math.PI/180)-a*Math.sin((window.paperVisual?.dir||0)*Math.PI/180))*8-time*3*6.7/(window.paperVisual?.T||6.7)),c]);let light=6*Math.sin(z*8-time*3+x*.4)*amp*attenuation;col=`rgb(${53+light},${132+light},${152+light})`}poly(v,col)}
// Canal walls and harbor margins; dimensions are illustrative scene units.
for(let x of [-.95,.95])box(x,.60,4.4,.09,6.8,.22,'#d9d8bd');
for(let x of [-5.1,-1.5,1.5,5.1])box(x,.1,-.15,.11,2.2,.4,'#c7bea0');
box(0,.72,1.4,3.5,.55,.17,'#a7aaa4');for(let x of [-.72,.72])box(x,-.2,1.4,.12,.18,.92,'#b8b7a2');for(let z of [1.13,1.67])box(0,.89,z,3.5,.035,.09,'#c3ba79');
if(window.paperVisual?.debris>0)box(0,level+.015,1.02,1.5,.35,window.paperVisual.debris*.25,'#7a6146');
// Wave-maker modules and laboratory instrument probes.
for(let i=0;i<24;i++){let x=-7.65+i*.66;box(x,-.15,-7.7,.6,.28,.65,'#515f60');box(x,.52,-7.7,.57,.16,.06,'#d5b847')}
for(let [x,z] of [[0,-5],[0,-2],[0,.8],[0,2.5],[0,4.5],[3,-4],[-3,-4]]){box(x,level,z,.035,.035,.5,'#eff0dc');box(x,level+.5,z,.18,.12,.07,'#cf713d')}
// Low streets make the landward laboratory terrain readable without inventing buildings.
for(let x of [-6,-4,-2,2,4,6])box(x,.37,4.6,.06,6,.015,'#988e61');
polys.sort((a,b)=>a.depth-b.depth);for(let o of polys){ctx.beginPath();o.p.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fillStyle=o.col;ctx.fill();ctx.strokeStyle=o.col;ctx.lineWidth=.4;ctx.stroke()}
let marks=[['Lake Pontchartrain',0,-5],['Harbor approaches',3,-.1],['Hammond Highway Bridge',0,1.4],['17th Street Canal',0,5.8],['Breach vicinity',1.2,4.4]];ctx.font='12px system-ui';marks.forEach(([name,x,z],i)=>{let p=project([x,.95,z]);ctx.fillStyle=i===4?'#af5837':'#f5f7ed';ctx.beginPath();ctx.arc(p[0],p[1],4,0,7);ctx.fill();ctx.fillStyle='#f8faf2e8';let tw=ctx.measureText(name).width;ctx.fillRect(p[0]+8,p[1]-17,tw+12,22);ctx.fillStyle='#203d40';ctx.fillText(name,p[0]+14,p[1]-2)});
if(window.paperVisual?.flow){let sign=window.paperVisual.flow;for(let j=0;j<4;j++){let z=2+(j+time*.5*sign)%4;if(z<2)z+=4;let a=project([0,level+.12,z]),b=project([0,level+.12,z+.25*sign]);ctx.strokeStyle='#eaf9f5';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke();ctx.beginPath();ctx.arc(b[0],b[1],3,0,7);ctx.fillStyle='#eaf9f5';ctx.fill()}}
if(selected){let s=sites[selected],p=project([s[1],1,s[2]]);ctx.strokeStyle='#e8a543';ctx.lineWidth=3;ctx.beginPath();ctx.arc(p[0],p[1],15,0,7);ctx.stroke()}}
function controls(){$('levelOut').textContent=(+$('level').value).toFixed(2)+' scene units';$('wavesOut').textContent=Math.round(+$('waves').value*100)+'%';$('speedOut').textContent=$('speed').value+'×'}for(let k of ['level','waves','speed'])$(k).oninput=controls;controls();$('pause').textContent=running?'Pause water':'Animate water';$('pause').onclick=()=>{running=!running;$('pause').textContent=running?'Pause water':'Animate water'};$('reset').onclick=()=>{yaw=-.6;el=.72;zoom=1};$('top').onclick=()=>{yaw=0;el=1.5;zoom=1};$('save').onclick=()=>{draw();let a=document.createElement('a');a.download='17th-street-canal-study.png';a.href=canvas.toDataURL('image/png');a.click()};canvas.onpointerdown=e=>{drag=[e.clientX,e.clientY];canvas.setPointerCapture(e.pointerId)};canvas.onpointermove=e=>{if(!drag)return;yaw+=(e.clientX-drag[0])*.006;el=Math.max(.2,Math.min(1.5,el+(e.clientY-drag[1])*.005));drag=[e.clientX,e.clientY]};canvas.onpointerup=canvas.onpointercancel=()=>drag=null;canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(1.7,zoom*Math.exp(-e.deltaY*.001)))},{passive:false});let last=0;function frame(t){if(running)time+=Math.min(.05,(t-last)/1000||0)*+$('speed').value;last=t;draw();requestAnimationFrame(frame)}requestAnimationFrame(frame);window.studio={getState:()=>({selected,yaw,el,zoom,running,time}),terrain};
